## This script works on windows and is used to deploy the GCP infrastructure based on the properties file generated by the Python algorithm. It checks for existing VMs and reuses them if they exist, ensuring idempotent deployments. It also sets up necessary firewall rules for Storm communication.

import ipaddress
import os
import re
import subprocess
import sys
import time

IS_WINDOWS = (os.name == 'nt')

# --- CONFIGURATION ---
DEFAULT_ZONE = "europe-west9-a"
MASTER_ZONE = DEFAULT_ZONE

# Resolve script directory (handles running from root or gcp_automations directory)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MASTER_STARTUP_SCRIPT = os.path.join(SCRIPT_DIR, "master_vm_startup.sh")
WORKER_STARTUP_SCRIPT = os.path.join(SCRIPT_DIR, "vm_startup.sh")

MASTER_NAME = "storm-nimbus"
MASTER_TYPE = "e2-medium" 
FIREWALL_RULE = "allow-storm-internal"
NETWORK = "default"

MACHINE_MAP = {
    (4, 16000): {"type": "n2-standard-4", "prefix": "cloud-core"},
    (2, 8000):  {"type": "e2-standard-2", "prefix": "fog-gateway"},
    (2, 4000):  {"type": "e2-medium",     "prefix": "worker-edge"},
    (1, 2000):  {"type": "e2-small",      "prefix": "worker-edge-light"},
    (1, 1000):  {"type": "e2-micro",      "prefix": "worker-iot"}
}

def parse_properties(file_path):
    with open(file_path, 'r') as f:
        content = f.read()
    
    match = re.search(r'hosts\.configuration\s*=\s*(.*?)(?:\n\n|\n[a-zA-Z]|$)', content, re.DOTALL)
    if not match:
        print("❌ Could not find hosts.configuration in the file.")
        sys.exit(1)
        
    hosts_str = match.group(1).replace('\n', '').replace('\\', '').strip()
    host_pairs = re.findall(r'\{(\d+),\s*(\d+)\}', hosts_str)
    hosts = [(int(cpu), int(ram)) for cpu, ram in host_pairs]

    # Parse zones with a more robust line-by-line approach to handle backslash continuations
    zones = []
    lines = content.split('\n')
    in_zones_section = False
    for line in lines:
        if 'hosts.zones' in line and '=' in line:
            in_zones_section = True
            # Extract the part after '='
            after_eq = line.split('=', 1)[1].strip()
            # Remove trailing backslash and add zones
            after_eq = after_eq.rstrip('\\').strip()
            if after_eq:
                zones.extend([z.strip() for z in after_eq.split(',') if z.strip()])
        elif in_zones_section:
            # Continue collecting zones until we hit a line that starts a new property or is blank+comment
            line = line.strip()
            if not line or line.startswith('#'):
                # End of zones section
                break
            if line and '=' in line and not any(c in line for c in ['{', ',']):
                # Hit a new property definition
                break
            # Remove trailing backslash
            line = line.rstrip('\\').strip()
            if line:
                zones.extend([z.strip() for z in line.split(',') if z.strip()])

    if len(zones) > 0:
        if len(zones) != len(hosts):
            print(
                f"❌ hosts.zones count ({len(zones)}) does not match hosts.configuration count ({len(hosts)})."
            )
            sys.exit(1)
    else:
        print(f"⚠️ hosts.zones not found in {file_path}. Falling back to default zone: {DEFAULT_ZONE}")
        zones = [DEFAULT_ZONE] * len(hosts)

    return hosts, zones

def run_gcloud(cmd, ignore_errors=False):
    # Print the command so you can track progress
    print(f"   [Debug] Running: {' '.join(cmd)}") 
    
    result = subprocess.run(cmd, shell=IS_WINDOWS, capture_output=True, text=True)
    if result.returncode != 0 and not ignore_errors:
        print(f"❌ Error running command: {' '.join(cmd)}\n{result.stderr}")
    return result.stdout.strip(), result.returncode

def vm_exists(vm_name, zone):
    """Checks if a VM already exists in GCP."""
    # Added --quiet so it does no wait for user input
    cmd = ['gcloud', 'compute', 'instances', 'describe', vm_name, f'--zone={zone}', '--format=value(name)', '--quiet']
    stdout, returncode = run_gcloud(cmd, ignore_errors=True)
    return returncode == 0

def get_vm_ip(vm_name, zone):
    """Fetches the internal IP of a VM."""
    import json
    ip_cmd = ['gcloud', 'compute', 'instances', 'describe', vm_name, f'--zone={zone}', '--format=json']
    stdout, _ = run_gcloud(ip_cmd)
    if stdout:
        data = json.loads(stdout)
        return data['networkInterfaces'][0]['networkIP']
    return ""

def validate_ip(ip_string):
    """Validates that a string is a valid IPv4 or IPv6 address."""
    try:
        ipaddress.ip_address(ip_string)
        return True
    except ValueError:
        return False

def ensure_storm_firewall_rule():
    """Ensures the Storm internal communication firewall rule exists."""
    check_cmd = ['gcloud', 'compute', 'firewall-rules', 'describe', FIREWALL_RULE, '--format=value(name)', '--quiet']
    _, returncode = run_gcloud(check_cmd, ignore_errors=True)

    if returncode == 0:
        print(f"🟢 Firewall rule {FIREWALL_RULE} already exists.")
        return

    print(f"🔐 Creating firewall rule {FIREWALL_RULE} for Storm internal communication...")
    create_cmd = [
        'gcloud', 'compute', 'firewall-rules', 'create', FIREWALL_RULE,
        f'--network={NETWORK}',
        '--allow=tcp:6700-6799,tcp:6627,tcp:2181,tcp:8080',
        '--source-tags=storm-node',
        '--target-tags=storm-node'
    ]
    run_gcloud(create_cmd)

def ensure_storm_ui_firewall_rule():
    """Ensures the Storm UI external access firewall rule exists (for experiments only)."""
    ui_rule = "allow-storm-ui-external"
    check_cmd = ['gcloud', 'compute', 'firewall-rules', 'describe', ui_rule, '--format=value(name)', '--quiet']
    _, returncode = run_gcloud(check_cmd, ignore_errors=True)

    if returncode == 0:
        print(f"🟢 Firewall rule {ui_rule} already exists.")
        return

    print(f"🌐 Creating firewall rule {ui_rule} for Storm UI external access (port 8080)...")
    create_cmd = [
        'gcloud', 'compute', 'firewall-rules', 'create', ui_rule,
        f'--network={NETWORK}',
        '--allow=tcp:8080',
        '--source-ranges=0.0.0.0/0',
        '--target-tags=storm-node'
    ]
    run_gcloud(create_cmd)

def main():
    if len(sys.argv) < 2:
        print("Usage: python deploy_gcp_from_properties.py <path_to_properties_file>")
        sys.exit(1)
        
    prop_file = sys.argv[1]
    hosts, zones = parse_properties(prop_file)
    print(f"🚀 Found {len(hosts)} worker hosts to deploy from {prop_file}.")

    # Ensure nodes can communicate over required Storm ports.
    ensure_storm_firewall_rule()
    ensure_storm_ui_firewall_rule()

    # ---------------------------------------------------------
    # 1. DEPLOY (OR REUSE) THE DEDICATED NIMBUS MASTER
    # ---------------------------------------------------------
    print("\n==================================================")
    if vm_exists(MASTER_NAME, MASTER_ZONE):
        print(f"🟢 Master {MASTER_NAME} already exists. Reusing it.")
    else:
        print(f"🧠 Deploying Dedicated Master: {MASTER_NAME} ({MASTER_TYPE}) in {MASTER_ZONE}")
        cmd_master = [
            'gcloud', 'compute', 'instances', 'create', MASTER_NAME,
            f'--machine-type={MASTER_TYPE}',
            f'--zone={MASTER_ZONE}',
            '--image-family=ubuntu-minimal-2404-lts-amd64',
            '--image-project=ubuntu-os-cloud',
            '--provisioning-model=SPOT',
            f'--metadata-from-file=startup-script={MASTER_STARTUP_SCRIPT}',
            '--tags=storm-node'
        ]
        run_gcloud(cmd_master)
        print("⏳ Waiting 5 seconds for network allocation...")
        time.sleep(5)
    
    nimbus_ip = get_vm_ip(MASTER_NAME, MASTER_ZONE)
    if not nimbus_ip:
        print("❌ Failed to retrieve Nimbus IP. Exiting.")
        sys.exit(1)
    if not validate_ip(nimbus_ip):
        print(f"❌ Invalid IP address format: {nimbus_ip}. Exiting.")
        sys.exit(1)
    print(f"✅ Master Internal IP is: {nimbus_ip}")

    # ---------------------------------------------------------
    # 2. DEPLOY (OR REUSE) THE INFRASTRUCTURE WORKERS
    # ---------------------------------------------------------
    name_counters = {v["prefix"]: 1 for v in MACHINE_MAP.values()}
    
    for index, (cpu, ram) in enumerate(hosts):
        zone = zones[index]
        if (cpu, ram) not in MACHINE_MAP:
            print(f"⚠️ Unknown config {cpu} CPU, {ram} RAM. Skipping.")
            continue
            
        vm_spec = MACHINE_MAP[(cpu, ram)]
        vm_name = f"{vm_spec['prefix']}-{name_counters[vm_spec['prefix']]}"
        name_counters[vm_spec['prefix']] += 1
        
        print(f"--------------------------------------------------")
        
        if vm_exists(vm_name, zone):
            print(f"🟢 Worker {index}: {vm_name} already exists in {zone}. Skipping creation.")
        else:
            print(f"⚙️ Deploying Worker {index}: {vm_name} ({vm_spec['type']}) in {zone}")
            
            cmd_worker = [
                'gcloud', 'compute', 'instances', 'create', vm_name,
                f'--machine-type={vm_spec["type"]}',
                f'--zone={zone}',
                '--image-family=ubuntu-minimal-2404-lts-amd64',
                '--image-project=ubuntu-os-cloud',
                '--provisioning-model=SPOT',
                f'--metadata-from-file=startup-script={WORKER_STARTUP_SCRIPT}',
                f'--metadata=nimbus-ip={nimbus_ip}',
                '--tags=storm-node'
            ]
            run_gcloud(cmd_worker)

    print("\n🎉 Infrastructure sync complete!")
    
    print(f"\n🔌 Connecting to Master: {MASTER_NAME}...")
    # On Windows, shell=True is needed to find the 'gcloud' executable (which is often a cmd/bat file)
    subprocess.run(["gcloud", "compute", "ssh", MASTER_NAME, f"--zone={MASTER_ZONE}"], shell=IS_WINDOWS)

if __name__ == "__main__":
    main()