## This script works on windows and is used to deploy the GCP infrastructure based on the properties file generated by the Python algorithm. It checks for existing VMs and reuses them if they exist, ensuring idempotent deployments. It also sets up necessary firewall rules for Storm communication.

import csv
import ipaddress
import os
import re
import subprocess
import sys
import time
from heapq import heappop, heappush

IS_WINDOWS = (os.name == 'nt')

# --- CONFIGURATION ---
DEFAULT_ZONE = "europe-west9-a"
MASTER_ZONE = DEFAULT_ZONE

# Resolve script directory (handles running from root or gcp_automations directory)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MASTER_STARTUP_SCRIPT = os.path.join(SCRIPT_DIR, "master_vm_startup.sh")
WORKER_STARTUP_SCRIPT = os.path.join(SCRIPT_DIR, "vm_startup.sh")

MASTER_NAME = "storm-nimbus"
MASTER_TYPE = "e2-medium" 
FIREWALL_RULE = "allow-storm-internal"
NETWORK = "default"

MACHINE_MAP = {
    (4, 16000): {"type": "n2-standard-4", "prefix": "cloud-core"},
    (2, 8000):  {"type": "e2-standard-2", "prefix": "fog-gateway"},
    (2, 4000):  {"type": "e2-medium",     "prefix": "worker-edge"},
    (1, 2000):  {"type": "e2-small",      "prefix": "worker-edge-light"},
    (1, 1000):  {"type": "e2-micro",      "prefix": "worker-iot"}
}


def collect_property_block(content, property_name):
    block_lines = []
    collecting = False

    for line in content.splitlines():
        stripped = line.strip()
        if not collecting:
            if stripped.startswith(property_name) and '=' in line:
                collecting = True
                block_lines.append(line.split('=', 1)[1].strip())
            continue

        if not stripped:
            if block_lines:
                break
            continue

        if stripped.startswith('#'):
            continue

        if re.match(r'^[A-Za-z_][\w.\-]*\s*=', stripped):
            break

        block_lines.append(stripped)

    return ' '.join(block_lines)


def parse_optional_float(raw_value):
    if raw_value is None:
        return None

    text_value = str(raw_value).strip()
    if not text_value:
        return None

    return float(text_value)


def parse_csv_like_values(block):
    normalized = block.replace('\\', ' ').replace('\n', ' ')
    return [value.strip() for value in normalized.split(',') if value.strip()]


def parse_topology_links(content):
    topology_block = collect_property_block(content, 'network.topology')
    if not topology_block:
        return []

    links = []
    for link_entry in re.findall(r'\{([^{}]+)\}', topology_block):
        values = [value.strip() for value in link_entry.split(',')]
        if len(values) < 4:
            continue

        links.append({
            'src': int(values[0]),
            'dst': int(values[1]),
            'bandwidth': int(values[2]),
            'latency': float(values[3]),
        })

    return links


def derive_network_profiles_from_topology(host_count, links):
    adjacency = {index: [] for index in range(host_count)}
    for link in links:
        src = link['src']
        dst = link['dst']
        bandwidth = link['bandwidth']
        latency = link['latency']

        if src == dst or bandwidth < 0 or latency < 0:
            continue

        if src in adjacency:
            adjacency[src].append((dst, latency, bandwidth))

    profiles = []
    target_node = 0

    for node_id in range(host_count):
        if node_id == target_node:
            profiles.append({'latency_ms': 0.0, 'bandwidth_mbit': None})
            continue

        queue = [(0.0, float('inf'), node_id)]
        best = {node_id: (0.0, float('inf'))}
        predecessor = {}
        best_path = None

        while queue:
            current_latency, current_bandwidth, current_node = heappop(queue)
            stored_latency, stored_bandwidth = best.get(current_node, (float('inf'), -1.0))
            if current_latency > stored_latency:
                continue
            if current_latency == stored_latency and current_bandwidth < stored_bandwidth:
                continue

            if current_node == target_node:
                best_path = (current_latency, current_bandwidth)
                break

            for neighbor, edge_latency, edge_bandwidth in adjacency.get(current_node, []):
                next_latency = current_latency + edge_latency
                next_bandwidth = min(current_bandwidth, edge_bandwidth)
                known_latency, known_bandwidth = best.get(neighbor, (float('inf'), -1.0))
                if next_latency < known_latency or (next_latency == known_latency and next_bandwidth > known_bandwidth):
                    best[neighbor] = (next_latency, next_bandwidth)
                    predecessor[neighbor] = current_node
                    heappush(queue, (next_latency, next_bandwidth, neighbor))

        if best_path is None:
            profiles.append({'latency_ms': None, 'bandwidth_mbit': None})
            continue

        latency_ms, bandwidth_mbit = best_path
        profiles.append({
            'latency_ms': latency_ms,
            'bandwidth_mbit': None if bandwidth_mbit == float('inf') else bandwidth_mbit,
        })

    return profiles


def format_numeric_value(value):
    if value is None:
        return None

    numeric_value = float(value)
    if numeric_value.is_integer():
        return str(int(numeric_value))
    return str(numeric_value)


def build_metadata_argument(metadata_items):
    metadata_pairs = [f"{key}={value}" for key, value in metadata_items.items() if value is not None]
    if not metadata_pairs:
        return None
    return '--metadata=' + ','.join(metadata_pairs)


def build_netem_command(latency_ms, bandwidth_mbit):
    tc_parts = []
    if latency_ms is not None:
        tc_parts.append(f"delay {format_numeric_value(latency_ms)}ms")
    if bandwidth_mbit is not None:
        tc_parts.append(f"rate {format_numeric_value(bandwidth_mbit)}mbit")

    if not tc_parts:
        return ''

    tc_arguments = ' '.join(tc_parts)
    return (
        'set -e; '
        'interface_name=$(ip route show default 2>/dev/null | head -n 1 | cut -d" " -f5); '
        'if [ -z "$interface_name" ]; then interface_name=ens4; fi; '
        'sudo tc qdisc del dev "$interface_name" root 2>/dev/null || true; '
        f'sudo tc qdisc add dev "$interface_name" root netem {tc_arguments}; '
        'sudo tc qdisc show dev "$interface_name"'
    )


def apply_netem_over_ssh(vm_name, zone, latency_ms, bandwidth_mbit):
    remote_command = build_netem_command(latency_ms, bandwidth_mbit)
    if not remote_command:
        return

    ssh_precheck_cmd = [
        'gcloud', 'compute', 'ssh', vm_name,
        f'--zone={zone}',
        '--quiet',
        '--command', 'echo SSH_OK',
    ]

    last_error = ""
    for attempt in range(1, 7):
        _, precheck_returncode, precheck_stderr = run_gcloud(
            ssh_precheck_cmd,
            ignore_errors=True,
            include_stderr=True,
        )
        if precheck_returncode == 0:
            print(f"SSH verification succeeded for {vm_name} on attempt {attempt}/6.")
            break

        last_error = precheck_stderr
        if attempt < 6:
            print(f"Attempt {attempt}/6: Host up but keys missing. Retrying...")
            time.sleep(10)
            continue

        print(f"SSH verification failed for {vm_name} after 6 attempts. Skipping NetEm shaping.")
        if last_error:
            print(f"   Error: {last_error}")
        return

    print(f"🌐 Applying NetEm shaping to {vm_name} in {zone}...")
    ssh_cmd = [
        'gcloud', 'compute', 'ssh', vm_name,
        f'--zone={zone}',
        '--quiet',
        '--command', remote_command,
    ]
    run_gcloud(ssh_cmd)

def parse_properties(file_path):
    with open(file_path, 'r') as f:
        content = f.read()

    hosts_block = collect_property_block(content, 'hosts.configuration')
    if not hosts_block:
        print("❌ Could not find hosts.configuration in the file.")
        sys.exit(1)

    host_entries = re.findall(r'\{([^{}]+)\}', hosts_block)
    if not host_entries:
        print("❌ Could not parse any host tuples from hosts.configuration.")
        sys.exit(1)

    hosts = []
    latency_values = []
    bandwidth_values = []
    for host_entry in host_entries:
        values = [value.strip() for value in host_entry.split(',')]
        if len(values) not in (2, 4):
            print(
                f"❌ Invalid hosts.configuration tuple: {host_entry}. Expected {{cpu, ram}} or {{cpu, ram, latency_ms, bandwidth_mbit}}."
            )
            sys.exit(1)

        cpu = int(values[0])
        ram = int(values[1])
        hosts.append((cpu, ram))

        if len(values) == 4:
            latency_values.append(parse_optional_float(values[2]))
            bandwidth_values.append(parse_optional_float(values[3]))

    if not latency_values:
        latency_block = collect_property_block(content, 'hosts.latency_ms')
        if latency_block:
            latency_values = [parse_optional_float(value) for value in parse_csv_like_values(latency_block)]

    if not bandwidth_values:
        bandwidth_block = collect_property_block(content, 'hosts.bandwidth_mbit')
        if bandwidth_block:
            bandwidth_values = [parse_optional_float(value) for value in parse_csv_like_values(bandwidth_block)]

    if latency_values and len(latency_values) != len(hosts):
        print(
            f"❌ hosts.latency_ms count ({len(latency_values)}) does not match hosts.configuration count ({len(hosts)})."
        )
        sys.exit(1)

    if bandwidth_values and len(bandwidth_values) != len(hosts):
        print(
            f"❌ hosts.bandwidth_mbit count ({len(bandwidth_values)}) does not match hosts.configuration count ({len(hosts)})."
        )
        sys.exit(1)

    topology_links = parse_topology_links(content)

    zones_block = collect_property_block(content, 'hosts.zones')
    if zones_block:
        zones = parse_csv_like_values(zones_block)
    else:
        print(f"⚠️ hosts.zones not found in {file_path}. Falling back to default zone: {DEFAULT_ZONE}")
        zones = [DEFAULT_ZONE] * len(hosts)

    if len(zones) != len(hosts):
        print(
            f"❌ hosts.zones count ({len(zones)}) does not match hosts.configuration count ({len(hosts)})."
        )
        sys.exit(1)

    if topology_links:
        network_profiles = derive_network_profiles_from_topology(len(hosts), topology_links)
    else:
        network_profiles = []
        for index in range(len(hosts)):
            network_profiles.append({
                'latency_ms': latency_values[index] if latency_values else None,
                'bandwidth_mbit': bandwidth_values[index] if bandwidth_values else None,
            })

    return hosts, zones, network_profiles

def run_gcloud(cmd, ignore_errors=False, include_stderr=False):
    # Print the command so you can track progress
    print(f"   [Debug] Running: {' '.join(cmd)}") 
    
    result = subprocess.run(cmd, shell=IS_WINDOWS, capture_output=True, text=True)
    if result.returncode != 0 and not ignore_errors:
        print(f"❌ Error running command: {' '.join(cmd)}\n{result.stderr}")
    if include_stderr:
        return result.stdout.strip(), result.returncode, result.stderr.strip()
    return result.stdout.strip(), result.returncode

def vm_exists(vm_name, zone):
    """Checks if a VM already exists in GCP."""
    # Added --quiet so it does no wait for user input
    cmd = ['gcloud', 'compute', 'instances', 'describe', vm_name, f'--zone={zone}', '--format=value(name)', '--quiet']
    stdout, returncode = run_gcloud(cmd, ignore_errors=True)
    return returncode == 0

def get_vm_ip(vm_name, zone):
    """Fetches the internal IP of a VM."""
    import json
    ip_cmd = ['gcloud', 'compute', 'instances', 'describe', vm_name, f'--zone={zone}', '--format=json']
    stdout, _ = run_gcloud(ip_cmd)
    if stdout:
        data = json.loads(stdout)
        return data['networkInterfaces'][0]['networkIP']
    return ""

def validate_ip(ip_string):
    """Validates that a string is a valid IPv4 or IPv6 address."""
    try:
        ipaddress.ip_address(ip_string)
        return True
    except ValueError:
        return False

def get_vm_status(vm_name, zone):
    """Fetches the current status of a VM."""
    status_cmd = ['gcloud', 'compute', 'instances', 'describe', vm_name, f'--zone={zone}', '--format=value(status)', '--quiet']
    stdout, returncode = run_gcloud(status_cmd, ignore_errors=True)
    if returncode != 0:
        return ""
    return stdout.strip()

def wait_for_vm_status(vm_name, zone, expected_status="RUNNING", timeout_seconds=300):
    """Waits until a VM reaches the expected status or times out."""
    deadline = time.time() + timeout_seconds
    current_status = ""

    while time.time() < deadline:
        current_status = get_vm_status(vm_name, zone)
        if current_status == expected_status:
            return True
        time.sleep(5)

    print(f"⚠️ Timed out waiting for {vm_name} to reach {expected_status}. Current status: {current_status or 'unknown'}")
    return False

def ensure_vm_running(vm_name, zone):
    """Starts or resumes a VM if it exists but is not running."""
    status = get_vm_status(vm_name, zone)
    if not status:
        print(f"⚠️ Could not determine status for {vm_name} in {zone}.")
        return

    if status == "RUNNING":
        print(f"🟢 {vm_name} is already running in {zone}.")
        return

    if status == "TERMINATED":
        print(f"▶️ Starting {vm_name} in {zone} (current status: {status})...")
        run_gcloud(['gcloud', 'compute', 'instances', 'start', vm_name, f'--zone={zone}', '--quiet'])
        wait_for_vm_status(vm_name, zone, "RUNNING")
        return

    if status == "SUSPENDED":
        print(f"▶️ Resuming {vm_name} in {zone} (current status: {status})...")
        run_gcloud(['gcloud', 'compute', 'instances', 'resume', vm_name, f'--zone={zone}', '--quiet'])
        wait_for_vm_status(vm_name, zone, "RUNNING")
        return

    print(f"⚠️ {vm_name} is in {zone} with status {status}. No start action was taken.")

def ensure_storm_firewall_rule():
    """Ensures the Storm internal communication firewall rule exists."""
    check_cmd = ['gcloud', 'compute', 'firewall-rules', 'describe', FIREWALL_RULE, '--format=value(name)', '--quiet']
    _, returncode = run_gcloud(check_cmd, ignore_errors=True)

    if returncode == 0:
        print(f"🟢 Firewall rule {FIREWALL_RULE} already exists.")
        return

    print(f"🔐 Creating firewall rule {FIREWALL_RULE} for Storm internal communication...")
    create_cmd = [
        'gcloud', 'compute', 'firewall-rules', 'create', FIREWALL_RULE,
        f'--network={NETWORK}',
        '--allow=tcp:6700-6799,tcp:6627,tcp:2181,tcp:8080',
        '--source-tags=storm-node',
        '--target-tags=storm-node'
    ]
    run_gcloud(create_cmd)

def ensure_storm_ui_firewall_rule():
    """Ensures the Storm UI external access firewall rule exists (for experiments only)."""
    ui_rule = "allow-storm-ui-external"
    check_cmd = ['gcloud', 'compute', 'firewall-rules', 'describe', ui_rule, '--format=value(name)', '--quiet']
    _, returncode = run_gcloud(check_cmd, ignore_errors=True)

    if returncode == 0:
        print(f"🟢 Firewall rule {ui_rule} already exists.")
        return

    print(f"🌐 Creating firewall rule {ui_rule} for Storm UI external access (port 8080)...")
    create_cmd = [
        'gcloud', 'compute', 'firewall-rules', 'create', ui_rule,
        f'--network={NETWORK}',
        '--allow=tcp:8080',
        '--source-ranges=0.0.0.0/0',
        '--target-tags=storm-node'
    ]
    run_gcloud(create_cmd)

def deploy_master(master_name, master_type, zone, startup_script):
    """Deploys the Nimbus master VM if it doesn't already exist."""
    print("\n==================================================")
    if vm_exists(master_name, zone):
        print(f"🟢 Master {master_name} already exists. Reusing it.")
        ensure_vm_running(master_name, zone)
        return

    print(f"🧠 Deploying Dedicated Master: {master_name} ({master_type}) in {zone}")
    cmd_master = [
        'gcloud', 'compute', 'instances', 'create', master_name,
        f'--machine-type={master_type}',
        f'--zone={zone}',
        '--image-family=ubuntu-minimal-2404-lts-amd64',
        '--image-project=ubuntu-os-cloud',
        '--provisioning-model=SPOT',
        f'--metadata-from-file=startup-script={startup_script}',
        '--tags=storm-node'
    ]
    run_gcloud(cmd_master)
    print("⏳ Waiting 5 seconds for network allocation...")
    time.sleep(5)

def get_and_validate_master_ip(master_name, zone):
    """Retrieves and validates the master VM's internal IP."""
    nimbus_ip = get_vm_ip(master_name, zone)
    if not nimbus_ip:
        print("❌ Failed to retrieve Nimbus IP. Exiting.")
        sys.exit(1)
    if not validate_ip(nimbus_ip):
        print(f"❌ Invalid IP address format: {nimbus_ip}. Exiting.")
        sys.exit(1)
    
    print(f"✅ Master Internal IP is: {nimbus_ip}")
    return nimbus_ip

def deploy_workers(hosts, zones, network_profiles, machine_map, nimbus_ip, worker_startup_script):
    """Deploys worker VMs based on the hosts configuration."""
    name_counters = {v["prefix"]: 1 for v in machine_map.values()}
    
    for index, (cpu, ram) in enumerate(hosts):
        zone = zones[index]
        network_profile = network_profiles[index]
        if (cpu, ram) not in machine_map:
            print(f"⚠️ Unknown config {cpu} CPU, {ram} RAM. Skipping.")
            continue
            
        vm_spec = machine_map[(cpu, ram)]
        vm_name = f"{vm_spec['prefix']}-{name_counters[vm_spec['prefix']]}"
        name_counters[vm_spec['prefix']] += 1
        
        print(f"--------------------------------------------------")
        
        if vm_exists(vm_name, zone):
            print(f"🟢 Worker {index}: {vm_name} already exists in {zone}. Skipping creation.")
            ensure_vm_running(vm_name, zone)
            apply_netem_over_ssh(vm_name, zone, network_profile['latency_ms'], network_profile['bandwidth_mbit'])
        else:
            print(f"⚙️ Deploying Worker {index}: {vm_name} ({vm_spec['type']}) in {zone}")

            metadata_argument = build_metadata_argument({
                'nimbus-ip': nimbus_ip,
                'netem-latency-ms': format_numeric_value(network_profile['latency_ms']),
                'netem-bandwidth-mbit': format_numeric_value(network_profile['bandwidth_mbit']),
            })
            
            cmd_worker = [
                'gcloud', 'compute', 'instances', 'create', vm_name,
                f'--machine-type={vm_spec["type"]}',
                f'--zone={zone}',
                '--image-family=ubuntu-minimal-2404-lts-amd64',
                '--image-project=ubuntu-os-cloud',
                '--provisioning-model=SPOT',
                f'--metadata-from-file=startup-script={worker_startup_script}',
                '--tags=storm-node'
            ]
            if metadata_argument:
                cmd_worker.insert(len(cmd_worker) - 1, metadata_argument)
            run_gcloud(cmd_worker)
            wait_for_vm_status(vm_name, zone, "RUNNING")
            apply_netem_over_ssh(vm_name, zone, network_profile['latency_ms'], network_profile['bandwidth_mbit'])

def main():
    if len(sys.argv) < 2:
        print("Usage: python deploy_gcp_from_properties.py <path_to_properties_file>")
        sys.exit(1)
        
    prop_file = sys.argv[1]
    hosts, zones, network_profiles = parse_properties(prop_file)
    print(f"🚀 Found {len(hosts)} worker hosts to deploy from {prop_file}.")

    # Ensure nodes can communicate over required Storm ports.
    ensure_storm_firewall_rule()
    ensure_storm_ui_firewall_rule()

    # 1. DEPLOY (OR REUSE) THE DEDICATED NIMBUS MASTER
    deploy_master(MASTER_NAME, MASTER_TYPE, MASTER_ZONE, MASTER_STARTUP_SCRIPT)
    
    # 2. GET MASTER IP
    nimbus_ip = get_and_validate_master_ip(MASTER_NAME, MASTER_ZONE)

    # 3. DEPLOY (OR REUSE) THE INFRASTRUCTURE WORKERS
    deploy_workers(hosts, zones, network_profiles, MACHINE_MAP, nimbus_ip, WORKER_STARTUP_SCRIPT)

    print("\n🎉 Infrastructure sync complete!")
    
    print(f"\n🔌 Connecting to Master: {MASTER_NAME}...")
    # On Windows, shell=True is needed to find the 'gcloud' executable (which is often a cmd/bat file)
    subprocess.run(["gcloud", "compute", "ssh", MASTER_NAME, f"--zone={MASTER_ZONE}"], shell=IS_WINDOWS)

if __name__ == "__main__":
    main()